Block range guarantee - Mercury
smartcontractkit/chainlink-relay pull request #95
Opened 2023-04-18 23:03 UTC by vyzaldysanchez

Goes with: https://github.com/smartcontractkit/chainlink/pull/9022

2023-04-21 23:15 UTC, jmank88 commented
Bumping libocr and updating loop here to unblock you: https://github.com/smartcontractkit/chainlink-relay/pull/101

2023-06-01 18:45 UTC, jmank88 commented on .tool-versions
> +golang 1.20.3
```suggestion
golang 1.20.4
```

2023-06-01 18:45 UTC, jmank88 commented on go.mod
> +	github.com/golang/protobuf v1.5.3 // indirect
Is this tidied? `indirect` is out of place here.

2023-06-05 21:07 UTC, jmank88 requested changes
We need to slow down and get all the pieces in to a consistent re-viewable state before merging.

2023-06-06 15:49 UTC, jmank88 requested changes
LGTM but we need to wait on libocr, yeah?

2023-06-06 22:21 UTC, samsondav approved these changes

2023-06-06 22:23 UTC, jmank88 approved these changes

2023-06-06 22:26 UTC, merged